/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PplepolicyRouteImport } from './routes/pplepolicy'
import { Route as IndexRouteImport } from './routes/index'

const PplepolicyRoute = PplepolicyRouteImport.update({
  id: '/pplepolicy',
  path: '/pplepolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pplepolicy': typeof PplepolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pplepolicy': typeof PplepolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pplepolicy': typeof PplepolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pplepolicy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pplepolicy'
  id: '__root__' | '/' | '/pplepolicy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PplepolicyRoute: typeof PplepolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pplepolicy': {
      id: '/pplepolicy'
      path: '/pplepolicy'
      fullPath: '/pplepolicy'
      preLoaderRoute: typeof PplepolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PplepolicyRoute: PplepolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
